# -*- coding: utf-8 -*-
"""Hugging face speech to text.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o7ChN4LqWzdggU80pfHNQiXTO88kmfRr

## Installing necessary libraries
"""

!pip install transformers datasets torchaudio soundfile librosa

import transformers
from transformers import pipeline
print(transformers.__version__)

import librosa      #package for analysing and manipulating audio files
import torch        #package for running ML models for comuter vision and deep learning
import numpy as np
import IPython.display as display

from transformers import Wav2Vec2ForCTC, Wav2Vec2Tokenizer       #to finetune a speech recognition model and tokenize texts from speech

tokenizer = Wav2Vec2Tokenizer.from_pretrained("facebook/wav2vec2-base-960h")
model = Wav2Vec2ForCTC.from_pretrained("facebook/wav2vec2-base-960h")

audio, sampling_rate = librosa.load("/content/sample_data/harvard.wav",sr = 16000)
audio, sampling_rate

display.Audio("/content/sample_data/harvard.wav", autoplay = True)

input_values = tokenizer(audio, return_tensors = "pt").input_values
input_values

logits = model(input_values).logits
logits

predicted_ids = torch.argmax(logits, dim = -1)
transcriptions = tokenizer.decode(predicted_ids[0])

transcriptions